### PR TITLE
Update gradle

### PR DESCRIPTION
**Pull request by joker1007**
Update gradle to support Java-11.

### CODE REVIEW

**Comment by repeatedly** [comment]
Thanks for the patch!
Could you add your sign to the commit with `-s`?

**Comment by joker1007** [comment]
Thank you for your response!
I've added the signature.

**Review by cosmo0920 — APPROVED** [review]
LGTM!

**Comment by cosmo0920** [comment]
@okkez How about this change?

**Comment by okkez** [comment]
Thanks!

**Pull request merged**
